//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace demoTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
        public string StaffName { get; set; }
        [Required]
        public Nullable<System.DateTime> DOB { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email Address")]

        [Required]
        public string StaffEmail { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required]
        public string StaffPhone { get; set; }
    }
}
