//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTraining.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingDBEntities : DbContext
    {
        public TrainingDBEntities()
            : base("name=TrainingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
        public virtual DbSet<TraineeEnrollment> TraineeEnrollments { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<TrainerEnrollment> TrainerEnrollments { get; set; }

        public Controllers.AuthenController AuthenController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.CategoriesController CategoriesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.HomeController HomeController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.CoursesController CoursesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.StaffsController StaffsController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.TraineesController TraineesController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.TopicsController TopicsController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.TrainersController TrainersController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.TraineeEnrollmentsController TraineeEnrollmentsController
        {
            get => default;
            set
            {
            }
        }

        public Controllers.TrainerEnrollmentsController TrainerEnrollmentsController
        {
            get => default;
            set
            {
            }
        }
    }
}
