//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace demoTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.TrainerEnrollments = new HashSet<TrainerEnrollment>();
        }
    
        public int TrainerID { get; set; }
        [Required]

        public string TrainerName { get; set; }
        [Required]
        public Nullable<System.DateTime> DOB { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required]
        public string TrainerEmail { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required]
        public string TrainerPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerEnrollment> TrainerEnrollments { get; set; }
    }
}
